#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 OpenTS contributors
# See LICENSE.md for applicable additional terms and warranty disclaimers.

"""Writes the build identity headers and the string-name table the engine includes.

opents_version.h follows the VERSION file and changes only when a release cycle opens.
opents_build.h follows HEAD and changes with every commit. opents_strings.h lists every
TXT_ identifier in code/language/language.h for the UI shell's [[TXT_NAME]] references, and
opents_language.h holds the text of each one from the string tables in language.rc.
A header is rewritten only when its contents change, so an ordinary rebuild does not
recompile its consumers.

Usage: generate_headers.py <source root> <output directory> [--official]
"""

import os
import re
import subprocess
import sys

LICENSE = """/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2026 OpenTS contributors
 *
 * See LICENSE.md for applicable additional terms and warranty disclaimers.
 ******************************************************************************/
"""

ARCH = "arm64"


def fail(message):
    sys.stderr.write("error: generate_headers.py: %s\n" % message)
    sys.exit(1)


def git(root, *arguments):
    """Runs git in the source tree and returns its trimmed output, or None on any failure."""
    try:
        result = subprocess.run(["git"] + list(arguments), cwd=root, stdout=subprocess.PIPE,
                                stderr=subprocess.DEVNULL, universal_newlines=True)
    except OSError:
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def write_if_changed(path, content):
    try:
        with open(path, encoding="utf-8") as existing:
            if existing.read() == content:
                return
    except OSError:
        pass
    with open(path, "w", encoding="utf-8") as output:
        output.write(content)


def version_header(root):
    with open(os.path.join(root, "VERSION"), encoding="utf-8") as file:
        version = file.read().strip()
    match = re.fullmatch(r"(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?", version)
    if not match:
        fail("VERSION holds %r, which is not a SemVer version without build metadata" % version)
    major, minor, patch = (int(part) for part in match.group(1, 2, 3))

    # The packed form spends one byte on each component, and the save and network stamps are
    # compared for exact equality, so a component that does not fit would collide.
    for name, value in (("major", major), ("minor", minor), ("patch", patch)):
        if value > 255:
            fail("version component %s is %d; the packed version stamp allows at most 255" % (name, value))

    packed = (major << 16) | (minor << 8) | patch
    prerelease = 1 if match.group(4) else 0
    content = LICENSE + """
/* Generated by platform/macos/generate_headers.py. Edits are overwritten by the next build. */

#pragma once

#define OPENTS_VERSION_MAJOR  %d
#define OPENTS_VERSION_MINOR  %d
#define OPENTS_VERSION_PATCH  %d

/* The save and network stamps. A prerelease is not distinguished here: it carries the
   identity of the release it leads up to. */
#define OPENTS_VERSION_PACKED 0x%X

#define OPENTS_VERSION        "%s"
#define OPENTS_IS_PRERELEASE  %d

#define OPENTS_ARCH "%s"
""" % (major, minor, patch, packed, version, prerelease, ARCH)
    return version, content


def branch_name(root):
    branch = git(root, "rev-parse", "--abbrev-ref", "HEAD")
    if branch and branch != "HEAD":
        return branch

    # A detached HEAD reports its branch as the word HEAD, which names nothing. Report a ref
    # that points at the commit instead, preferring a tag.
    refs = git(root, "for-each-ref", "--points-at", "HEAD", "--format=%(refname)",
               "refs/tags", "refs/heads", "refs/remotes")
    if refs:
        names = [ref.strip() for ref in refs.splitlines()]
        for prefix in ("refs/tags/", "refs/heads/", "refs/remotes/"):
            for ref in names:
                # refs/remotes/<remote>/HEAD only records where a remote points.
                if ref.startswith(prefix) and not ref.endswith("/HEAD"):
                    return ref[len(prefix):]
    return "unknown"


def stamp_header(root, version, official):
    commit = "unknown"
    branch = "unknown"
    date = "unknown"
    dirty = 0

    # A build from a source archive has no repository; the banner reports what it does not know.
    if os.path.exists(os.path.join(root, ".git")):
        commit = git(root, "rev-parse", "--short", "HEAD") or "unknown"
        branch = branch_name(root)
        date = git(root, "log", "-1", "--format=%cd", "--date=format:%Y-%m-%d %H:%M:%S") or "unknown"
        # Untracked files do not make the built code differ from the commit.
        status = git(root, "status", "--porcelain", "--untracked-files=no")
        dirty = 1 if status else 0

    description = "%s on %s%s" % (commit, branch, " (modified)" if dirty else "")
    if official or commit == "unknown":
        display = "%s (%s)" % (version, ARCH)
    elif dirty:
        display = "%s (%s, modified, %s)" % (version, commit, ARCH)
    else:
        display = "%s (%s, %s)" % (version, commit, ARCH)

    return LICENSE + """
/* Generated by platform/macos/generate_headers.py. Edits are overwritten by the next build. */

#pragma once

#include "opents_version.h"

#define OPENTS_COMMIT            "%s"
#define OPENTS_BRANCH            "%s"
#define OPENTS_COMMIT_DATE       "%s"
#define OPENTS_COMMIT_DIRTY      %d

/* The commit and branch as one line, for reports with no room to lay the parts out. */
#define OPENTS_BUILD_DESCRIPTION "%s"

/* The version as the player sees it. A build that is not marked official names its commit. */
#define OPENTS_VERSION_DISPLAY   "%s"
""" % (commit, branch, date, dirty, description, display)


def strings_header(root):
    path = os.path.join(root, "code", "language", "language.h")
    entries = []
    with open(path, encoding="utf-8", errors="replace") as file:
        for line in file:
            match = re.match(r"#define (TXT_[A-Za-z0-9_]+)[ \t]+([0-9]+)", line)
            if match:
                entries.append('\t{ "%s", %s },\n' % match.group(1, 2))
    if not entries:
        fail("%s defines no TXT_ identifiers" % path)

    return LICENSE + """
/* Generated by platform/macos/generate_headers.py from language.h. Edits are overwritten by the next build. */

#pragma once

struct OpenTSStringName
{
	char const * Name;
	int Id;
};

inline constexpr OpenTSStringName OpenTSStringNames[] = {
%s};

inline constexpr int OpenTSStringNameCount = %d;
""" % ("".join(entries), len(entries))


def string_ids(root):
    ids = {}
    with open(os.path.join(root, "code", "language", "language.h"), encoding="utf-8", errors="replace") as file:
        for line in file:
            match = re.match(r"#define (TXT_[A-Za-z0-9_]+)[ \t]+([0-9]+)", line)
            if match:
                ids[match.group(1)] = int(match.group(2))
    return ids


RC_ESCAPES = {"n": "\n", "t": "\t", "r": "\r", "a": "\a", "\\": "\\", '"': '"', "0": "\0"}


def decode_rc_string(body):
    """Decodes the body of a resource-script string literal, where "" stands for one quote."""
    text = []
    index = 0
    while index < len(body):
        character = body[index]
        if character == '"' and body[index + 1:index + 2] == '"':
            text.append('"')
            index += 2
        elif character == "\\" and index + 1 < len(body):
            escape = body[index + 1]
            if escape == "x":
                digits = re.match(r"[0-9A-Fa-f]{1,4}", body[index + 2:]).group(0)
                text.append(chr(int(digits, 16)))
                index += 2 + len(digits)
                continue
            text.append(RC_ESCAPES.get(escape, escape))
            index += 2
        else:
            text.append(character)
            index += 1
    return "".join(text)


def c_literal(text):
    """Spells text as a C string literal, escaping by UTF-8 byte so no escape runs into a digit."""
    out = []
    for byte in text.encode("utf-8"):
        character = chr(byte)
        if character == "\\":
            out.append("\\\\")
        elif character == '"':
            out.append('\\"')
        elif character == "\n":
            out.append("\\n")
        elif character == "\t":
            out.append("\\t")
        elif 0x20 <= byte < 0x7F and character != "?":
            out.append(character)
        else:
            out.append("\\%03o" % byte)
    return '"' + "".join(out) + '"'


def language_header(root):
    path = os.path.join(root, "code", "language", "language.rc")
    with open(path, encoding="utf-8-sig") as file:
        script = file.read()
    ids = string_ids(root)

    strings = {}
    for block in re.finditer(r"^STRINGTABLE[^\n]*\n\s*BEGIN\b(.*?)^END\b", script, re.M | re.S):
        for entry in re.finditer(r'(TXT_[A-Za-z0-9_]+)\s*,?\s*"((?:[^"]|"")*)"', block.group(1)):
            name = entry.group(1)
            if name not in ids:
                fail("%s names %s, which language.h does not define" % (path, name))
            if ids[name] in strings:
                fail("%s defines the string with id %d twice" % (path, ids[name]))
            strings[ids[name]] = decode_rc_string(entry.group(2))
    if not strings:
        fail("%s holds no string tables" % path)

    rows = "".join("\t{ %d, %s },\n" % (key, c_literal(strings[key])) for key in sorted(strings))
    return LICENSE + """
/* Generated by platform/macos/generate_headers.py from language.rc. Edits are overwritten by the next build. */

#pragma once

struct OpenTSLanguageString
{
	int Id;
	char const * Text;
};

/* Sorted by Id. */
inline constexpr OpenTSLanguageString OpenTSLanguageStrings[] = {
%s};

inline constexpr int OpenTSLanguageStringCount = %d;
""" % (rows, len(strings))


def main(arguments):
    if len(arguments) < 2 or len(arguments) > 3 or (len(arguments) == 3 and arguments[2] != "--official"):
        fail("usage: generate_headers.py <source root> <output directory> [--official]")
    root, output = arguments[0], arguments[1]
    os.makedirs(output, exist_ok=True)

    version, content = version_header(root)
    write_if_changed(os.path.join(output, "opents_version.h"), content)
    write_if_changed(os.path.join(output, "opents_build.h"), stamp_header(root, version, len(arguments) == 3))
    write_if_changed(os.path.join(output, "opents_strings.h"), strings_header(root))
    write_if_changed(os.path.join(output, "opents_language.h"), language_header(root))


if __name__ == "__main__":
    main(sys.argv[1:])
